"""Minimal local stub: the chart verb draws terminal bars and time series."""

from collections.abc import Sequence

def clear_figure() -> None: ...
def theme(name: str) -> None: ...
def simple_bar(
    x: Sequence[str],
    y: Sequence[int],
    *,
    width: int | None = ...,
    marker: str | None = ...,
    color: str | None = ...,
    title: str | None = ...,
) -> None: ...
def bar(
    x: Sequence[int] | Sequence[str],
    y: Sequence[int],
    *,
    color: str | None = ...,
    width: float | None = ...,
    orientation: str | None = ...,
) -> None: ...
def xticks(ticks: Sequence[int], labels: Sequence[str] | None = ...) -> None: ...
def yticks(ticks: Sequence[int], labels: Sequence[str] | None = ...) -> None: ...
def plot_size(width: int | None = ..., height: int | None = ...) -> None: ...
def build() -> str: ...
def uncolorize(string: str) -> str: ...
