"""Minimal local stub: sempipe builds one bar chart with it."""

from typing import Any

class BaseElement: ...

class Drawing:
    def __init__(self, filename: str = ..., size: tuple[Any, Any] = ..., **extra: Any) -> None: ...
    def add(self, element: BaseElement) -> BaseElement: ...
    def rect(
        self, insert: tuple[Any, Any] = ..., size: tuple[Any, Any] = ..., **extra: Any
    ) -> BaseElement: ...
    def text(self, text: str, insert: tuple[Any, Any] = ..., **extra: Any) -> BaseElement: ...
    def tostring(self) -> str: ...
